Reservations are kept when existing

diff --git a/templates/slurm_reservations.sh.j2 b/templates/slurm_reservations.sh.j2
--- a/templates/slurm_reservations.sh.j2
+++ b/templates/slurm_reservations.sh.j2
@@ -3,7 +3,14 @@
 
 
 function create_reservation {
-    scontrol del reservation $5
+    # Test if reservation already exists: FIXME: if we need to modify the reservation, this would have to be changed
+    # however, as immediate reservation often fails (see the workaround below), it's safer not to touch existing ones
+    # when we can.
+    scontrol show reservation $5
+    if ([ $? -eq 0 ]); then
+        return 0
+    fi
+    # scontrol del reservation $5
     scontrol create reservation account=$1 duration=infinite CoreCnt=$2 Nodes=$3 starttime=now flags=magnetic PartitionName=$4 ReservationName=$5
     if ([ $? -eq 0 ]); then
         scontrol create reservation account=$1 duration=infinite CoreCnt=$2 Nodes=$3 starttime=now+3days flags=magnetic PartitionName=$4 ReservationName=$5
